name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script to check file mod
      env:
        cfile: sstow.sh
      run: |
        file $cfile
        stat -c %a $cfile
